@local = http://localhost:8181
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY1ZTM2NGQ0YTFiZTM2YTg2NDU5MGQiLCJuYW1lIjoiYWFhYmJiIiwiaWF0IjoxNjA5OTUwMTgxfQ.ne_J3SsxGV8paD9KKtAu8UNugj1i2AxwKwpp-sXg50w
POST {{local}}/sheba/users
content-type: application/json

{
    "name" : "tal",
    "email": "tal12@gmail.com",
    "password": "taltal12"
}

###

POST {{local}}/sheba/auth
content-type: application/json

{
    "email": "tal12@gmail.com",
    "password":"taltal12"
}

###

GET {{local}}/sheba/projects/my-projects
content-type: application/json
x-auth-token: {{token}}

###

POST {{local}}/sheba/projects/
content-type: application/json
x-auth-token: {{token}}

{
    "projectName":"TEST1" ,
    "projectDescription": "TESTYTEST 1" ,
    "projectTech": "ANGULAR"
    }

###

PUT  {{local}}/sheba/projects/5ff5eac8ab65495c3cd7985c
content-type: application/json
x-auth-token: {{token}}

{
    "projectName":"TEST22222222" ,
    "projectDescription": "TESTYTEST 1" ,
    "projectTech": "ANGULAR"
    }

###

POST {{local}}/sheba/users/favorites/5ff5ea8eab65495c3cd7985b
x-auth-token: {{token}}

